title: Index a list in Python
hero_image: images/banner.png
description: list indices in Python
original_url: 
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum: 
interests: 
technologies: "python"
site_areas:
steps:
  - title: List indices
